# -*- coding: utf-8 -*-
"""Bart_Metric_Calculations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovY2H3HhxulkM2jmtXUj7hnV32zy8iZI
"""

!pip install nltk rouge-score pandas

import pandas as pd
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

pred_df = pd.read_csv("bart_examples.csv")
real_df = pd.read_csv("cbb_headlines_11_2024.csv")

pred_df.columns = pred_df.columns.str.lower()
real_df.columns = real_df.columns.str.lower()

pred_df = pred_df.drop('prompt', axis=1)

# Ensure columns exist
assert "game_id" in pred_df.columns, "Prediction file missing GAME_ID column"
assert "headline" in real_df.columns, "Real headline file missing HEADLINE column"

merged = pred_df.merge(real_df[["game_id", "headline"]], on="game_id", how="inner")

print("Merged shape:", merged.shape)
print(merged.head())

smooth = SmoothingFunction().method1
rouge = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)

def compute_bleu(reference, hypothesis):
    return sentence_bleu(
        [reference.split()],
        hypothesis.split(),
        weights=(0.25, 0.25, 0.25, 0.25),
        smoothing_function=smooth
    )

def compute_rouge(reference, hypothesis):
    return rouge.score(reference, hypothesis)["rougeL"].fmeasure


bleu_scores = []
rouge_scores = []

print("\n=========== PER-GAME RESULTS ===========")

for _, row in merged.iterrows():
    real = row["headline_y"] # Changed from "headline"
    pred = row["headline_x"] # Changed from "predicted"

    bleu = compute_bleu(real, pred)
    rouge_score = compute_rouge(real, pred)

    bleu_scores.append(bleu)
    rouge_scores.append(rouge_score)

    print("\nGame:", row["game_id"])
    print("REAL :", real)
    print("PRED :", pred)
    print(f"BLEU-4:  {bleu:.4f}")
    print(f"ROUGE-L: {rouge_score:.4f}")

print("\n\n=========== SUMMARY ==========")
print(f"Avg BLEU-4:  {sum(bleu_scores) / len(bleu_scores):.4f}")
print(f"Avg ROUGE-L: {sum(rouge_scores) / len(rouge_scores):.4f}")