# -*- coding: utf-8 -*-
"""NCAA NLP Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15L6D_SiiQbUoLhz2yljAXTFofam6Omiz

# NCAA
"""

import requests
import pandas as pd
import time
from datetime import date, timedelta
from tqdm import tqdm


def get_cbb_game_dataframes(game_id):
    """
    Returns two DataFrames:
      1. meta_df: game_id + headline + description
      2. box_df: player boxscore + game_id
    """
    url = f"https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/summary?event={game_id}"
    data = requests.get(url).json()

    # --- HEADLINE & DESCRIPTION ---
    headline = (
        data.get("header", {}).get("headline")
        or data.get("article", {}).get("headline")
        or "No headline found"
    )
    article = data.get("article", {})
    description = article.get("description", "No description found")
    description = description.lstrip("—–- ").strip()

    meta_df = pd.DataFrame([{
        "game_id": game_id,
        "headline": headline,
        "description": description
    }])

    # --- BOX SCORE ---
    players = data.get("boxscore", {}).get("players", [])
    rows = []
    for team_entry in players:
        team = team_entry.get("team", {}).get("displayName", "")
        for stat_cat in team_entry.get("statistics", []):
            stat_names = stat_cat.get("names", [])
            for athlete in stat_cat.get("athletes", []):
                player_name = athlete.get("athlete", {}).get("displayName", "")
                stat_values = athlete.get("stats", [])
                row = {"game_id": game_id, "team": team, "player": player_name}
                for name, value in zip(stat_names, stat_values):
                    row[name] = value
                rows.append(row)
    box_df = pd.DataFrame(rows)

    return meta_df, box_df

def get_cbb_game_ids_for_date(date_str):
    """
    Return list of CBB game IDs for a given YYYYMMDD date string.
    Add groups=50 to include all Division I games.
    """
    url = (
        "https://site.api.espn.com/apis/site/v2/sports/basketball/"
        "mens-college-basketball/scoreboard"
    )
    params = {"dates": date_str, "groups": "50", "limit": "500"}
    r = requests.get(url, params=params)
    if r.status_code != 200:
        print(f"⚠️ Failed for {date_str}")
        return []
    data = r.json()
    return [event["id"] for event in data.get("events", [])]


def collect_cbb_game_ids(start_date, end_date):
    """Loop through a range of dates and collect all CBB game IDs."""
    current = start_date
    all_ids = []
    while current <= end_date:
        ds = current.strftime("%Y%m%d")
        ids = get_cbb_game_ids_for_date(ds)
        if ids:
            for gid in ids:
                all_ids.append({"date": ds, "game_id": gid})
        current += timedelta(days=1)
    return pd.DataFrame(all_ids)


def collect_cbb_season_data(game_id_df, delay=0.5):
    all_meta = []
    all_box = []

    for gid in tqdm(game_id_df["game_id"], desc="Fetching CBB games"):
        try:
            meta_df, box_df = get_cbb_game_dataframes(gid)
            all_meta.append(meta_df)
            all_box.append(box_df)
        except Exception as e:
            print(f"⚠️ Skipped {gid}: {e}")
        time.sleep(delay)

    meta_df_all = pd.concat(all_meta, ignore_index=True)
    box_df_all = pd.concat(all_box, ignore_index=True)
    return meta_df_all, box_df_all

start = date(2024, 11, 4)
end   = date(2025, 4, 7)

print("Collecting game IDs...")
game_id_df = collect_cbb_game_ids(start, end)
print(f"Collected {len(game_id_df)} games total")
game_id_df.to_csv(f"cbb_game_ids_{start.year}_{end.year}.csv", index=False)

meta_df_all, box_df_all = collect_cbb_season_data(game_id_df)

# Save results
meta_df_all.to_csv(f"cbb_headlines_{start.year}_{end.year}.csv", index=False)
box_df_all.to_csv(f"cbb_boxscores_{start.year}_{end.year}.csv", index=False)

print(f"\nSaved {len(meta_df_all)} headlines/descriptions and {len(box_df_all)} player stat rows.")